<?php
declare(strict_types=1);

require_once __DIR__ . '/includes/db_config.php';

$slug = clean_text($_GET['slug'] ?? '', 255);
$stmt = $pdo->prepare('SELECT * FROM blog_posts WHERE slug = :slug LIMIT 1');
$stmt->execute([':slug' => $slug]);
$post = $stmt->fetch();

if (!$post) {
    http_response_code(404);
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= e($post['title'] ?? 'Post not found') ?> | Writemize</title>
    <link rel="stylesheet" href="assets/css/app.css">
</head>
<body class="post-body">
    <header class="blog-nav">
        <a class="blog-brand" href="dashboard/index.php">
            <img src="assets/images/logo.png" alt="Writemize">
        </a>
        <a class="blog-back" href="dashboard/index.php">Dashboard</a>
    </header>

    <?php if (!$post): ?>
        <main class="post-shell post-empty">
            <p class="eyebrow">Writemize</p>
            <h1>Post not found</h1>
            <p>The requested Writemize post does not exist.</p>
        </main>
    <?php else: ?>
        <main>
            <section class="blog-hero">
                <div class="blog-hero-copy">
                    <p class="eyebrow"><?= e($post['focus_keyword']) ?></p>
                    <h1><?= e($post['title']) ?></h1>
                    <p class="blog-dek"><?= e($post['meta_description']) ?></p>
                    <div class="blog-stats">
                        <span>SEO <?= (int) $post['seo_score'] ?></span>
                        <span><?= (int) $post['word_count'] ?> words</span>
                        <span><?= e($post['reading_time']) ?></span>
                        <span><?= e($post['status']) ?></span>
                    </div>
                </div>
                <div class="blog-hero-media">
                    <?php if (!empty($post['image_url'])): ?>
                        <img src="<?= e($post['image_url']) ?>" alt="">
                    <?php else: ?>
                        <div class="blog-image-fallback">
                            <img src="assets/images/logo.png" alt="">
                        </div>
                    <?php endif; ?>
                </div>
            </section>

            <section class="post-shell">
                <aside class="post-sidebar">
                    <img src="assets/images/logo.png" alt="Writemize">
                    <strong>Generated by Writemize</strong>
                    <span>Scout, Radar, Quill, Warden, Pulse, Publisher</span>
                </aside>
                <article class="post-article">
                    <?= $post['html'] ?>
                </article>
            </section>
        </main>
    <?php endif; ?>
</body>
</html>
