<?php
declare(strict_types=1);

header('Content-Type: application/json; charset=utf-8');

require_once __DIR__ . '/../includes/db_config.php';

function respond(int $statusCode, array $payload): void
{
    http_response_code($statusCode);
    echo json_encode($payload, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
    exit;
}

function readJsonBody(): array
{
    $rawBody = file_get_contents('php://input');
    if ($rawBody === false || trim($rawBody) === '') {
        return [];
    }

    $decoded = json_decode($rawBody, true);
    if (!is_array($decoded)) {
        respond(400, [
            'success' => false,
            'logs' => ['Invalid JSON request body.'],
            'error' => 'Invalid JSON request body.'
        ]);
    }

    return $decoded;
}

function sanitizeText(string $value, int $maxLength): string
{
    $value = trim(strip_tags($value));
    $value = preg_replace('/\s+/', ' ', $value) ?? $value;
    return mb_substr($value, 0, $maxLength);
}

function extractWebsiteContext(string $url, array &$logs): string
{
    $logs[] = 'Scout fetching website content.';

    $ch = curl_init($url);
    curl_setopt_array($ch, [
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_FOLLOWLOCATION => true,
        CURLOPT_MAXREDIRS => 4,
        CURLOPT_CONNECTTIMEOUT => 10,
        CURLOPT_TIMEOUT => 20,
        CURLOPT_USERAGENT => 'WritemizeBot/1.0 (+https://writemize.local)',
        CURLOPT_SSL_VERIFYPEER => false,
        CURLOPT_SSL_VERIFYHOST => 0,
    ]);

    $html = curl_exec($ch);
    $curlError = curl_error($ch);
    $httpCode = (int)curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);

    if ($html === false || $curlError !== '' || $httpCode >= 400) {
        $logs[] = 'Scout could not read the website, continuing with URL and business inputs.';
        return '';
    }

    $text = html_entity_decode(strip_tags((string)$html), ENT_QUOTES | ENT_HTML5, 'UTF-8');
    $text = preg_replace('/\s+/', ' ', $text) ?? $text;
    $text = trim($text);

    if ($text === '') {
        $logs[] = 'Scout found no readable page text, continuing with URL and business inputs.';
        return '';
    }

    $logs[] = 'Scout extracted website context.';
    return mb_substr($text, 0, 5000);
}

function parseAiContent(string $content): array
{
    $content = trim($content);
    $content = preg_replace('/^```(?:json|html)?\s*/i', '', $content) ?? $content;
    $content = preg_replace('/```$/', '', $content) ?? $content;
    $content = trim($content);

    $decoded = json_decode($content, true);
    if (is_array($decoded)) {
        return $decoded;
    }

    return [
        'title' => 'Generated Blog Article',
        'meta_description' => 'A high-quality SEO article generated by Writemize.',
        'seo_score' => 92,
        'word_count' => str_word_count(strip_tags($content)),
        'reading_time' => '7 min',
        'status' => 'Generated',
        'publish_url' => '',
        'html' => $content,
    ];
}

function sanitizeGeneratedHtml(string $html): string
{
    $html = preg_replace('/<script\b[^>]*>.*?<\/script>/is', '', $html) ?? $html;
    $html = preg_replace('/<style\b[^>]*>.*?<\/style>/is', '', $html) ?? $html;
    $html = preg_replace('/\son[a-z]+\s*=\s*(".*?"|\'.*?\'|[^\s>]+)/is', '', $html) ?? $html;
    $html = preg_replace('/(href|src)\s*=\s*([\'"])\s*javascript:.*?\2/is', '$1="#"', $html) ?? $html;
    return trim($html);
}

function generateFeaturedImageUrl(string $apiKey, string $topic, array &$logs): ?string
{
    $topic = sanitizeText($topic, 220);
    if ($topic === '') {
        $logs[] = 'DALL-E 3 skipped because no article topic was available.';
        return null;
    }

    $logs[] = 'DALL-E 3 generating featured image for: ' . $topic;

    $imagePrompt = sprintf(
        'Create a polished editorial blog featured image for the topic "%s". Modern digital marketing and AI theme, premium SaaS style, professional, bright focal point, no text, no logos, 16:9 composition.',
        $topic
    );

    $payload = [
        'model' => 'dall-e-3',
        'prompt' => $imagePrompt,
        'n' => 1,
        'size' => '1024x1024',
        'quality' => 'standard',
    ];

    $ch = curl_init('https://api.openai.com/v1/images/generations');
    curl_setopt_array($ch, [
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_POST => true,
        CURLOPT_POSTFIELDS => json_encode($payload, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE),
        CURLOPT_HTTPHEADER => [
            'Content-Type: application/json',
            'Authorization: Bearer ' . $apiKey,
        ],
        CURLOPT_CONNECTTIMEOUT => 15,
        CURLOPT_TIMEOUT => 120,
        CURLOPT_SSL_VERIFYPEER => false,
        CURLOPT_SSL_VERIFYHOST => 0,
    ]);
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);

    $response = curl_exec($ch);
    $curlError = curl_error($ch);
    $httpCode = (int)curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);

    if ($response === false || $curlError !== '') {
        $logs[] = 'DALL-E 3 cURL request failed: ' . $curlError;
        return null;
    }

    $decoded = json_decode((string)$response, true);
    if (!is_array($decoded)) {
        $logs[] = 'DALL-E 3 returned an invalid response.';
        return null;
    }

    if ($httpCode < 200 || $httpCode >= 300 || isset($decoded['error'])) {
        $logs[] = 'DALL-E 3 image generation failed: ' . ($decoded['error']['message'] ?? 'Unknown image API error.');
        return null;
    }

    $imageUrl = (string)($decoded['data'][0]['url'] ?? '');
    if ($imageUrl === '') {
        $logs[] = 'DALL-E 3 completed but did not return an image URL.';
        return null;
    }

    $logs[] = 'DALL-E 3 featured image URL received.';
    return $imageUrl;
}

$logs = [
    'Pipeline request received.',
    'Validating Business Setup inputs.',
];

$request = readJsonBody();

$websiteUrl = sanitizeText((string)($request['website_url'] ?? ''), 2048);
$publishTime = sanitizeText((string)($request['publish_time'] ?? ''), 32);
$businessName = sanitizeText((string)($request['business_name'] ?? ''), 160);
$companyName = sanitizeText((string)($request['company_name'] ?? ''), 160);

if ($websiteUrl === '' || !filter_var($websiteUrl, FILTER_VALIDATE_URL)) {
    respond(422, [
        'success' => false,
        'logs' => array_merge($logs, ['Website URL validation failed.']),
        'error' => 'Please enter a valid website URL.'
    ]);
}

$scheme = strtolower((string)parse_url($websiteUrl, PHP_URL_SCHEME));
if (!in_array($scheme, ['http', 'https'], true)) {
    respond(422, [
        'success' => false,
        'logs' => array_merge($logs, ['Website URL must use HTTP or HTTPS.']),
        'error' => 'Website URL must start with http:// or https://.'
    ]);
}

$apiKey = getenv('OPENAI_API_KEY') ?: ($openAiKey ?? '');
if (!is_string($apiKey) || trim($apiKey) === '') {
    respond(500, [
        'success' => false,
        'logs' => array_merge($logs, ['OpenAI API key missing in includes/db_config.php.']),
        'error' => 'OpenAI API key is not configured.'
    ]);
}

$logs[] = 'OpenAI API key loaded securely from includes/db_config.php.';
$logs[] = 'Scheduled for: ' . ($publishTime !== '' ? $publishTime : 'Not provided');
$websiteContext = extractWebsiteContext($websiteUrl, $logs);
$logs[] = 'Radar preparing SEO strategy.';
$logs[] = 'Quill preparing long-form HTML article prompt.';

$systemPrompt = <<<'PROMPT'
You are Writemize, an autonomous 24/7 expert technical writer, SEO strategist, editor, and publishing assistant.
Create a real, high-quality, SEO-optimized blog article in clean semantic HTML.
Do not include markdown fences. Do not invent unverifiable claims. Use practical, expert-level explanations and a confident professional tone.
Return only a valid JSON object with these exact keys:
title, meta_description, focus_keyword, seo_score, word_count, reading_time, status, publish_url, html.
The html value must be a complete blog body using HTML tags such as article, header, h1, p, h2, h3, ul, li, strong, and section.
PROMPT;

$userPrompt = sprintf(
    "Business name: %s\nCompany name: %s\nWebsite URL: %s\nPreferred publish time: %s\nWebsite context:\n%s\n\nGenerate a polished technical blog article of about 1200-1600 words. Optimize for search intent, include a strong SEO title, meta description, introduction, clear headings, examples, actionable takeaways, and a conclusion. The article must be ready to display directly in the Writemize dashboard preview.",
    $businessName !== '' ? $businessName : 'Not provided',
    $companyName !== '' ? $companyName : 'Not provided',
    $websiteUrl,
    $publishTime !== '' ? $publishTime : 'Not provided',
    $websiteContext !== '' ? $websiteContext : 'Website text was unavailable. Use the URL and business inputs to infer a safe, broadly useful article angle.'
);

$payload = [
    'model' => 'gpt-5.6',
    'messages' => [
        ['role' => 'system', 'content' => $systemPrompt],
        ['role' => 'user', 'content' => $userPrompt],
    ],
    'temperature' => 0.7,
    'response_format' => ['type' => 'json_object'],
];

$logs[] = 'Calling OpenAI Chat Completions API with model gpt-5.6.';

$ch = curl_init('https://api.openai.com/v1/chat/completions');
curl_setopt_array($ch, [
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_POST => true,
    CURLOPT_POSTFIELDS => json_encode($payload, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE),
    CURLOPT_HTTPHEADER => [
        'Content-Type: application/json',
        'Authorization: Bearer ' . $apiKey,
    ],
    CURLOPT_CONNECTTIMEOUT => 15,
    CURLOPT_TIMEOUT => 120,
    CURLOPT_SSL_VERIFYPEER => false,
    CURLOPT_SSL_VERIFYHOST => 0,
]);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);

$response = curl_exec($ch);
$curlError = curl_error($ch);
$httpCode = (int)curl_getinfo($ch, CURLINFO_HTTP_CODE);
curl_close($ch);

if ($response === false || $curlError !== '') {
    respond(502, [
        'success' => false,
        'logs' => array_merge($logs, ['OpenAI cURL request failed.']),
        'error' => 'OpenAI request failed: ' . $curlError
    ]);
}

$decodedResponse = json_decode((string)$response, true);
if (!is_array($decodedResponse)) {
    respond(502, [
        'success' => false,
        'logs' => array_merge($logs, ['OpenAI returned a non-JSON response.']),
        'error' => 'OpenAI returned an invalid response.'
    ]);
}

if ($httpCode < 200 || $httpCode >= 300 || isset($decodedResponse['error'])) {
    $message = $decodedResponse['error']['message'] ?? 'OpenAI API request failed.';
    respond(502, [
        'success' => false,
        'logs' => array_merge($logs, ['OpenAI API returned an error.']),
        'error' => $message
    ]);
}

$content = (string)($decodedResponse['choices'][0]['message']['content'] ?? '');
if ($content === '') {
    respond(502, [
        'success' => false,
        'logs' => array_merge($logs, ['OpenAI response did not include article content.']),
        'error' => 'OpenAI response did not include article content.'
    ]);
}

$article = parseAiContent($content);
$articleHtml = sanitizeGeneratedHtml((string)($article['html'] ?? ''));

if (trim(strip_tags($articleHtml)) === '') {
    respond(502, [
        'success' => false,
        'logs' => array_merge($logs, ['Generated article HTML was empty.']),
        'error' => 'Generated article HTML was empty.'
    ]);
}

$imageTopic = (string)($article['title'] ?? $article['focus_keyword'] ?? ($businessName !== '' ? $businessName : ($companyName !== '' ? $companyName : 'AI business blog')));
$imageUrl = generateFeaturedImageUrl($apiKey, $imageTopic, $logs);

$logs[] = 'Warden parsed and validated generated article HTML.';
$logs[] = 'Pulse prepared article preview data.';
$logs[] = 'Pipeline completed successfully.';

respond(200, [
    'success' => true,
    'logs' => $logs,
    'article' => [
        'title' => sanitizeText((string)($article['title'] ?? 'Generated Blog Article'), 220),
        'meta_description' => sanitizeText((string)($article['meta_description'] ?? ''), 320),
        'focus_keyword' => sanitizeText((string)($article['focus_keyword'] ?? ''), 120),
        'seo_score' => (int)($article['seo_score'] ?? 92),
        'word_count' => (int)($article['word_count'] ?? str_word_count(strip_tags($articleHtml))),
        'reading_time' => sanitizeText((string)($article['reading_time'] ?? '7 min'), 40),
        'status' => sanitizeText((string)($article['status'] ?? 'Generated'), 60),
        'publish_url' => sanitizeText((string)($article['publish_url'] ?? $websiteUrl), 2048),
        'image_url' => $imageUrl,
        'html' => $articleHtml,
    ],
]);
